### ISSUE TITLE
Add "Mozmill Tests" and "Infrastructure" components from "Mozilla QA" product

### ISSUE THREAD

**Issue by whimboo** [jdm/bugsahoy#104]
We want to get the above mentioned components added to bugsahoy. It's actually interesting that for Mozmill Tests we don't have an entry yet. I'm sure I created that formerly.

@jdm what would be the best way to get this done beside the already existent oneanddone entry? The format of the file is somewhat hard to understand. So your feedback would be welcome.

**Comment by Standard8** [comment]
Can this be closed now PR #105 is closed?

**Comment by whimboo** [comment]
Yes, looks like we missed to close this issue. I will file a follow-up to also get them replaced with Marionette.
