### ISSUE TITLE
Add "mozilla_ci_tools" to the list of projects

### ISSUE THREAD

**Issue by armenzg** [jdm/bugsahoy#126]
The project is in here:
https://github.com/armenzg/mozilla_ci_tools

This is a "Test Automation" type of project.
Most issues will be python related, however, I believe that is me simply adding "python" as a label.

It seems that people are using "mentored" as the label.

What is the label for easy bugs?

What does this mean?
> For a pull request, it just requires adding a new `addGithubComponentMapping' call.

**Comment by armenzg** [comment]
I believe this is all it is required.

**Comment by jdm** [comment]
I don't believe easy bugs from github projects are supported, for reasons that I can't recall right now.

**Comment by armenzg** [comment]
Thank you Josh!
