### ISSUE TITLE
Twitter Feed Location

### ISSUE THREAD

**Issue by jaredpetersen** [jdm/bugsahoy#137]
The twitter feed is displayed in some weird ways depending on how many bugs are returned and the filters used. Here are the different non-desirable looks:

No categories specified (http://www.joshmatthews.net/bugsahoy/) or if bugs weren't found (http://www.joshmatthews.net/bugsahoy/?media=1&diamond=1) results in the twitter feed being slighly lower than the results box, probably because of some javascript hiding stuff:

![bugsahoymain](https://cloud.githubusercontent.com/assets/8802128/7526799/eb6df58e-f4c9-11e4-94de-e10187346f18.png)

Only one bug is returned and a suggestion box is shown (http://www.joshmatthews.net/bugsahoy/?py=1&diamond=1) results in the twitter feed moving below the results box (the twitter feed is placed below the suggestion box in cases where more bugs are pulled in):

![bugsahoypythondiamond](https://cloud.githubusercontent.com/assets/8802128/7526806/128777c6-f4ca-11e4-87c7-afd0d024dd87.PNG)

**Comment by jdm** [comment]
Yeah, CSS is hard for me. We should probably look into a proper three column design, which is what I've worked on via trial and error so far.

**Comment by jaredpetersen** [comment]
Just looked back at the site today since I haven't been keeping up with the project that closely lately. I think that we need to move to something like Bootstrap, because the page really doesn't resize very well. It looks like some Bootstrap design elements are in place but the page organization stuff is not. The elements are just all over the place, particularly with somewhat larger screen sizes and on mobile. Switching to a proper three column design like what you mentioned will be very beneficial.

**Comment by jdm** [comment]
Fixed by #160!
