### ISSUE TITLE
Add Firefox Accounts

### ISSUE THREAD

**Issue by vladikoff** [jdm/bugsahoy#140]
Hello @jdm 

Could we add a Cloud Services section to http://www.joshmatthews.net/bugsahoy/? ?

Here are the first 3 repos, might have more in the future:
### 1
https://github.com/mozilla/fxa-content-server
 label:"good first bug" 

https://github.com/mozilla/fxa-content-server/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+bug%22

### 2
https://github.com/mozilla/fxa-auth-server/
  label:"good-first-bug"

https://github.com/mozilla/fxa-auth-server/issues?q=is%3Aopen+is%3Aissue+label%3Agood-first-bug

### 3
https://github.com/mozilla/fxa-oauth-server
  label:"good-first-bug"

**Comment by jdm** [comment]
Sorry for missing this. Are any of these still useful to add?
