### ISSUE TITLE
Make "Simple bugs" option more discoverable to new contributors

### ISSUE THREAD

**Issue by arai-a** [jdm/bugsahoy#143]
It seems that "Simple bugs" option tend to be overlooked by new contributors.  It's now placed at the bottom of the sidebar (needs scroll to see it), and unchecked by default.  This option is important for new contributors.  It should be better to make it more discoverable.

There will be several way:
 * move it to the top of the sidebar
 * check it by default
 * show hint when it's not checked

**Comment by arai-a** [comment]
here's a mock up for showing hint.
clicking "Yes" button checks "Simple bugs" checkbox and refreshes the list.
screenshot: https://gist.github.com/arai-a/6c50644ca9f0f9801a8d
branch: https://github.com/arai-a/bugsahoy/tree/simple-hint

**Comment by jdm** [comment]
These are good points. I hadn't considered moving it or showing a hint before; unfortunately, checking it by default isn't realistic because of the extreme difference in performance the bugzilla queries exhibit that make use of it.

**Comment by jdm** [comment]
Thanks for the branch! I made some changes and pushed to master :) Feel free to make PRs for any further improvements!

**Comment by arai-a** [comment]
wow, thank you for quick reply and followup :D
