### ISSUE TITLE
Filter by Assigned/Not Assigned

### ISSUE THREAD

**Issue by bkudryavtsev** [jdm/bugsahoy#149]
It would be a nice feature to filter bugs which are "Assigned to: Nobody; OK to take it and work on it" and those who already have already been assigned.

**Comment by jdm** [comment]
That's already an option: https://github.com/jdm/bugsahoy/blob/master/index.html#L136

**Comment by bkudryavtsev** [comment]
Oh. The name is a little unclear. I suggest it should be something like "Bugs not assigned"

**Comment by bkudryavtsev** [comment]
"Owner" can be confused with the bug creator, not the assignee.

**Comment by jdm** [comment]
Good point! I'd probably go with "Unassigned bugs". Want to make a pull request with that change?

**Comment by bkudryavtsev** [comment]
Sure!
