### ISSUE TITLE
Mixed content makes the site unusable in latests browser versions

### ISSUE THREAD

**Issue by lopis** [jdm/bugsahoy#162]
jQuery is being pulled via HTTP white the site itself opens in HTTPS. Browsers lately started blocking this (YMMV). Found in Firefox 51 and Chromium 53.

```
Blocked loading mixed active content “http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js”[Learn More] bugsahoy
ReferenceError: jQuery is not defined[Learn More]
```

**Comment by jdm** [comment]
Fixed by 2621c3c. Thanks for reporting it!
