### ISSUE TITLE
Language mapping for mozilla-releng/services is not working

### ISSUE THREAD

**Issue by marco-c** [jdm/bugsahoy#174]
The label on mozilla-releng/services is `3.lang: python`. Probably one of the special characters is causing issues.

**Comment by jdm** [comment]
Fixed by 72c0eee4f6dcdec34e8b38546e841859862f0855.

**Comment by marco-c** [comment]
Thanks ;)

**Comment by marco-c** [comment]
There's something strange happening now though, e.g. https://www.joshmatthews.net/bugsahoy/?py=1 lists https://github.com/mozilla-releng/services/pull/761, which is a pull request and doesn't have the label.

**Comment by marco-c** [comment]
From a cursory look, it seems like the same is happening with other repositories.

**Comment by jdm** [comment]
Fixed by fcf76c98e0f5e4ac0a524d6f4f1a4b5ed8b0a30e.

**Comment by marco-c** [comment]
Thanks again ;)
