### ISSUE TITLE
Add-ons Bugs in Bugs Ahoy

### ISSUE THREAD

**Issue by caitmuenster** [jdm/bugsahoy#183]
Hi there! I'm hoping we can update some add-ons bugs in Bugs Ahoy. 

1. WebExtensions bugs were recently moved to their own Product in Bugzilla, and unfortunately [WE good-first-bugs](https://mzl.la/2yq1XA8) no longer appear in Bugs Ahoy: 

![screen shot 2018-06-21 at 10 17 58 am](https://user-images.githubusercontent.com/23342476/41734713-9cc6a722-753c-11e8-9cce-1fa90f2efd94.png)

These bugs are good for developers who know JavaScript (and in very rare cases, C++). 

2. There are currently no bugs listed for addons.mozilla.org -- possibly because AMO bugs are now on Github. Could we pull in AMO good first bugs from the [AMO server](https://github.com/mozilla/addons-server/labels/contrib%3A%20good%20first%20bug) (good for folks with Python and Django skills) and [AMO frontend](https://github.com/mozilla/addons-frontend/labels/contrib%3A%20good%20first%20bug) (good for folks who know React and Redux)? 

3. Firefox Marketplace has been decommissioned. Could it be removed from the Web Development category? 

Thank you so much!

**Comment by jdm** [comment]
Fixed in 11f4c010c1cb86c1cf2b0db7461c30b348630bb2, fc0ee5bb7b0a0f98711216a9d7c42d09231891ee, and 167d37ebf697e2ac4980773b224d8dcf3974c4a2. Thanks!
