### ISSUE TITLE
online help for bugsahoy

### ISSUE THREAD

**Issue by k0s** [jdm/bugsahoy#47]
It would be nice for me, as a developer, to be able to see on http://www.joshmatthews.net/bugsahoy/ how to file bugs/github issues/whatever that will be slurped up by bugsahoy.  While the way to file bugzilla bugs is baked into my brain, I have had many people ask how to do this, so online instructions might be nice.  I don't know how to file github issues to be picked up by bugsahoy, so I generally don't.  If there was online help, I probably would.

It would be nice for contributors, IMHO, to have more online help about the role of bugsahoy in the Mozilla ecosystem.  Even a brief description and a page of links would be a big help.

This could just be static HTML.  It should be linked to from the top of the page for easy access (TBH, I'd move the footer, " Bugs Ahoy! is written by Josh Matthews (get the source!) " to the top of the page too, and probably replicate it in the "help").

**Comment by jaredpetersen** [comment]
@jdm Should this issue be closed? Someone already submitted a pull request that was merged into the project.

**Comment by jdm** [comment]
Seem reasonable.
