### ISSUE TITLE
Display the component the bug is in

### ISSUE THREAD

**Issue by Rik** [jdm/bugsahoy#67]
It's especially useful for Gaia because it will tell you which application is concerned.

**Comment by jaredpetersen** [comment]
What about displaying it on another line in the popup that displays when a user mouses over a bug?

![componenetdisplay](https://cloud.githubusercontent.com/assets/8802128/6514310/575199b0-c336-11e4-809f-dc1e4d0c8cae.png)

**Comment by jdm** [comment]
That's a good idea! Please do :)

**Comment by jaredpetersen** [comment]
This issue can be closed as a fix was merged in pull #130.
