### ISSUE TITLE
bugsahoy should use include_fields to limit search results

### ISSUE THREAD

**Issue by globau** [jdm/bugsahoy#86]
bugsahoy current requests all information about a bug (including attachment) when searching bugzilla.

it will be much quicker to use "include_fields" to limit the results to just the fields which bugsahoy uses.

i don't know exactly what fields bugsahoy uses, but as an example if you only use the "id" and "summary", append the following to your bzapi query string:
include_fields=id,summary

**Comment by jdm** [comment]
We've done this for a while.
